[package]
name = "lidx"
version = "0.1.0"
authors = ["wxd <wxdwfc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "build.rs"

[dependencies]
libc = "0.2.0"
rand = "0.6.5"